# Generated by Django 5.1.1 on 2024-09-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='disliked_users',
            field=models.ManyToManyField(related_name='disliked_by', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_by', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='matches',
            field=models.ManyToManyField(related_name='matched_with', to='users.userprofile'),
        ),
    ]
